services:
  - elasticsearch

language: go

go:
  - 1.3
  - 1.4
  - 1.5

script:
  - go get -t ./...
  - go build ./lib/
  - cd ./lib/ && go test -v -host localhost -loaddata
  - go install
  
build_image: drydock/u14golpls:tip
